# Generated by Django 6.0.1 on 2026-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this object",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this object is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this credential expires",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("git_ssh_key", "Git SSH Key"),
                            ("git_https_token", "Git HTTPS Token"),
                            ("git_username_password", "Git Username/Password"),
                            ("docker_hub", "Docker Hub"),
                            ("aws_ecr", "AWS ECR"),
                            ("quay_io", "Quay.io"),
                            ("generic_registry", "Generic Container Registry"),
                            ("api_key", "API Key"),
                            ("oauth_token", "OAuth Token"),
                            ("custom", "Custom Credential"),
                        ],
                        db_index=True,
                        help_text="Type of credential being stored",
                        max_length=50,
                        verbose_name="Credential Type",
                    ),
                ),
                (
                    "encrypted_data",
                    models.TextField(
                        help_text="Encrypted credential data (JSON format)",
                        verbose_name="Encrypted Data",
                    ),
                ),
                (
                    "encryption_key_id",
                    models.CharField(
                        editable=False,
                        help_text="Identifier of the encryption key used",
                        max_length=255,
                        verbose_name="Encryption Key ID",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this credential was last used",
                        null=True,
                        verbose_name="Last Used At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credential",
                "verbose_name_plural": "Credentials",
                "ordering": ["name", "credential_type"],
                "indexes": [
                    models.Index(
                        fields=["credential_type"],
                        name="credentials_credent_d70998_idx",
                    ),
                    models.Index(
                        fields=["last_used_at"], name="credentials_last_us_9f7e76_idx"
                    ),
                    models.Index(
                        fields=["encryption_key_id"],
                        name="credentials_encrypt_4490f9_idx",
                    ),
                ],
            },
        ),
    ]
