# Generated by Django 6.0.1 on 2026-01-08 09:59

import apps.branding.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrandingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this object",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this object is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this object",
                        verbose_name="Description",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        help_text="The brand name to display in the UI",
                        max_length=255,
                        verbose_name="Brand Name",
                    ),
                ),
                (
                    "replacement_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object containing text/brand replacement rules",
                        verbose_name="Replacement Rules",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default branding template",
                        verbose_name="Is Default",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding Template",
                "verbose_name_plural": "Branding Templates",
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["brand_name"], name="branding_br_brand_n_b6758f_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="branding_br_is_defa_4472de_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandingAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_index=True,
                        help_text="Original filename of the asset",
                        max_length=255,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("favicon", "Favicon"),
                            ("theme", "Theme CSS"),
                            ("background", "Background Image"),
                            ("icon", "Icon"),
                            ("font", "Font File"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        help_text="Type of branding asset",
                        max_length=50,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The asset file",
                        max_length=1024,
                        upload_to=apps.branding.models.get_asset_upload_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="File size in bytes",
                        verbose_name="File Size",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        editable=False,
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this asset",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this asset is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The branding template this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="branding.brandingtemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branding Asset",
                "verbose_name_plural": "Branding Assets",
                "ordering": ["file_type", "file_name"],
                "indexes": [
                    models.Index(
                        fields=["template", "file_type"],
                        name="branding_br_templat_03bdbd_idx",
                    ),
                    models.Index(
                        fields=["file_type"], name="branding_br_file_ty_7dd2ac_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="branding_br_is_acti_6efd2d_idx"
                    ),
                ],
                "unique_together": {("template", "file_name", "file_type")},
            },
        ),
    ]
