# Generated by Django 6.0.1 on 2026-01-08 09:59

import apps.pipelines.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registries", "0001_initial"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON metadata for the object",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                            ("cloning", "Cloning Repository"),
                            ("building", "Building"),
                            ("packaging", "Packaging"),
                            ("pushing", "Pushing to Registry"),
                        ],
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "steps_to_execute",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of pipeline steps to execute",
                        verbose_name="Steps to Execute",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when execution started",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when execution completed or failed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        help_text="Complete execution logs",
                        verbose_name="Execution Logs",
                    ),
                ),
                (
                    "log_file",
                    models.FileField(
                        blank=True,
                        help_text="Log file for detailed execution information",
                        max_length=1024,
                        null=True,
                        upload_to=apps.pipelines.models.get_pipeline_log_path,
                        verbose_name="Log File",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        default="main",
                        help_text="Git branch to build from",
                        max_length=255,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        blank=True,
                        help_text="Specific commit hash to build",
                        max_length=40,
                        verbose_name="Commit Hash",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("docker_image", "Docker Image"),
                            ("zip", "ZIP File"),
                            ("tarball", "Tarball"),
                            ("directory", "Directory"),
                        ],
                        default="docker_image",
                        help_text="Type of build output to generate",
                        max_length=20,
                        verbose_name="Output Type",
                    ),
                ),
                (
                    "image_tag",
                    models.CharField(
                        blank=True,
                        help_text="Custom tag for Docker images",
                        max_length=100,
                        verbose_name="Image Tag",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the worker processing this pipeline",
                        max_length=100,
                        verbose_name="Worker ID",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Execution progress (0-100)",
                        verbose_name="Progress Percentage",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        help_text="Currently executing pipeline step",
                        max_length=100,
                        verbose_name="Current Step",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Details about execution failure",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "branding_template_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of branding template to apply",
                        null=True,
                        verbose_name="Branding Template ID",
                    ),
                ),
                (
                    "build_arguments",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional arguments for the build process",
                        verbose_name="Build Arguments",
                    ),
                ),
                (
                    "environment_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Environment variables for the build",
                        verbose_name="Environment Variables",
                    ),
                ),
                (
                    "git_repository",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source Git repository for the build",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_runs",
                        to="repositories.gitrepository",
                        verbose_name="Git Repository",
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registry to push Docker images to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_runs",
                        to="registries.containerregistry",
                        verbose_name="Container Registry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Run",
                "verbose_name_plural": "Pipeline Runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this object expires",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[
                            ("docker_image", "Docker Image"),
                            ("zip", "ZIP File"),
                            ("tarball", "Tarball"),
                            ("directory", "Directory"),
                        ],
                        help_text="Type of build output",
                        max_length=20,
                        verbose_name="Output Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        help_text="Current status of the build output",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the generated file (for ZIP/TARBALL outputs)",
                        max_length=1024,
                        null=True,
                        verbose_name="File Path",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated file (for downloadable outputs)",
                        max_length=1024,
                        null=True,
                        upload_to=apps.pipelines.models.get_build_output_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="File Size",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Docker image URL (for image outputs)",
                        max_length=1024,
                        null=True,
                        verbose_name="Image URL",
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 checksum of the output file",
                        max_length=64,
                        null=True,
                        verbose_name="SHA256 Checksum",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this output has been downloaded",
                        verbose_name="Download Count",
                    ),
                ),
                (
                    "build_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the build",
                        verbose_name="Build Metadata",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        help_text="Pipeline run that produced this output",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_outputs",
                        to="pipelines.pipelinerun",
                        verbose_name="Pipeline Run",
                    ),
                ),
            ],
            options={
                "verbose_name": "Build Output",
                "verbose_name_plural": "Build Outputs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["status"], name="pipelines_p_status_4989ca_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["started_at"], name="pipelines_p_started_842741_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["completed_at"], name="pipelines_p_complet_302a2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["git_repository"], name="pipelines_p_git_rep_b8ab01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["registry"], name="pipelines_p_registr_1a4719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["output_type"], name="pipelines_p_output__77ae5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["worker_id"], name="pipelines_p_worker__c6e3aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["created_at"], name="pipelines_p_created_219979_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildoutput",
            index=models.Index(
                fields=["pipeline_run"], name="pipelines_b_pipelin_f986bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildoutput",
            index=models.Index(
                fields=["output_type"], name="pipelines_b_output__8a8964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildoutput",
            index=models.Index(fields=["status"], name="pipelines_b_status_27dca0_idx"),
        ),
        migrations.AddIndex(
            model_name="buildoutput",
            index=models.Index(
                fields=["created_at"], name="pipelines_b_created_a69a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildoutput",
            index=models.Index(
                fields=["expires_at"], name="pipelines_b_expires_52f516_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="buildoutput",
            unique_together={("pipeline_run", "output_type")},
        ),
    ]
