"""initial migration

Revision ID: f036c06e4c08
Revises: cc870034365b
Create Date: 2025-10-30 14:04:05.683468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f036c06e4c08'
down_revision = 'cc870034365b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###