# Generated by Django 6.0.1 on 2026-01-08 09:59

import apps.registries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this object",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this object is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "registry_type",
                    models.CharField(
                        choices=[
                            ("docker_hub", "Docker Hub"),
                            ("aws_ecr", "Amazon ECR"),
                            ("quay_io", "Quay.io"),
                            ("github_registry", "GitHub Container Registry"),
                            ("gitlab_registry", "GitLab Container Registry"),
                            ("azure_registry", "Azure Container Registry"),
                            ("google_registry", "Google Container Registry"),
                            ("generic", "Generic Registry"),
                        ],
                        default="docker_hub",
                        help_text="Type of container registry",
                        max_length=20,
                        verbose_name="Registry Type",
                    ),
                ),
                (
                    "base_image",
                    models.CharField(
                        default=apps.registries.models.get_default_base_image,
                        help_text="Source image to customize (e.g., open-webui/open-webui:main)",
                        max_length=255,
                        verbose_name="Base Image",
                    ),
                ),
                (
                    "target_image",
                    models.CharField(
                        default=apps.registries.models.get_default_target_image,
                        help_text="Target image name for custom builds (e.g., myrepo/custom-open-webui:v1.0)",
                        max_length=255,
                        verbose_name="Target Image",
                    ),
                ),
                (
                    "registry_url",
                    models.CharField(
                        blank=True,
                        help_text="Custom registry URL (for generic registries)",
                        max_length=255,
                        verbose_name="Registry URL",
                    ),
                ),
                (
                    "aws_account_id",
                    models.CharField(
                        blank=True,
                        help_text="AWS Account ID for ECR registries",
                        max_length=15,
                        verbose_name="AWS Account ID",
                    ),
                ),
                (
                    "aws_region",
                    models.CharField(
                        blank=True,
                        help_text="AWS region for ECR registries",
                        max_length=50,
                        verbose_name="AWS Region",
                    ),
                ),
                (
                    "repository_name",
                    models.CharField(
                        blank=True,
                        help_text="Repository name in the registry",
                        max_length=255,
                        verbose_name="Repository Name",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this registry has been successfully verified",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "verification_message",
                    models.TextField(
                        blank=True,
                        help_text="Details about the last verification attempt",
                        verbose_name="Verification Message",
                    ),
                ),
                (
                    "last_pushed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful image push",
                        null=True,
                        verbose_name="Last Pushed At",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credential for registry authentication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="container_registries",
                        to="credentials.credential",
                        verbose_name="Credential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Container Registry",
                "verbose_name_plural": "Container Registries",
                "ordering": ["name", "registry_type"],
                "indexes": [
                    models.Index(fields=["name"], name="registries__name_7ac67f_idx"),
                    models.Index(
                        fields=["registry_type"], name="registries__registr_21fb5e_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="registries__is_veri_77ddd9_idx"
                    ),
                    models.Index(
                        fields=["last_pushed_at"], name="registries__last_pu_0a0e7b_idx"
                    ),
                ],
                "unique_together": {("name", "registry_url")},
            },
        ),
    ]
