# Generated by Django 6.0.1 on 2026-01-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the object was first created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the object was last modified",
                        verbose_name="Last Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this object",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether this object is currently active",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        help_text="Full URL to the Git repository",
                        max_length=1024,
                        verbose_name="Repository URL",
                    ),
                ),
                (
                    "repository_type",
                    models.CharField(
                        choices=[
                            ("https", "HTTPS"),
                            ("ssh", "SSH"),
                            ("git", "Git Protocol"),
                        ],
                        default="https",
                        help_text="Protocol type for accessing the repository",
                        max_length=20,
                        verbose_name="Repository Type",
                    ),
                ),
                (
                    "default_branch",
                    models.CharField(
                        default="main",
                        help_text="Default branch to use for builds",
                        max_length=255,
                        verbose_name="Default Branch",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this repository has been successfully verified",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("failed", "Verification Failed"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        help_text="Current verification status",
                        max_length=50,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verification_message",
                    models.TextField(
                        blank=True,
                        help_text="Details about the last verification attempt",
                        verbose_name="Verification Message",
                    ),
                ),
                (
                    "is_experimental",
                    models.BooleanField(
                        default=True,
                        help_text="Experimental repositories are marked as such in the UI",
                        verbose_name="Is Experimental",
                    ),
                ),
                (
                    "last_commit_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the last known commit",
                        max_length=40,
                        verbose_name="Last Commit Hash",
                    ),
                ),
                (
                    "last_commit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of the last known commit",
                        null=True,
                        verbose_name="Last Commit Date",
                    ),
                ),
                (
                    "clone_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path where repository is cloned",
                        max_length=1024,
                        verbose_name="Clone Path",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional credential for repository access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="git_repositories",
                        to="credentials.credential",
                        verbose_name="Credential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git Repository",
                "verbose_name_plural": "Git Repositories",
                "ordering": ["name", "repository_type"],
                "indexes": [
                    models.Index(fields=["name"], name="repositorie_name_323607_idx"),
                    models.Index(
                        fields=["repository_type"],
                        name="repositorie_reposit_2d2740_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="repositorie_is_veri_eb6bab_idx"
                    ),
                    models.Index(
                        fields=["verification_status"],
                        name="repositorie_verific_196edb_idx",
                    ),
                    models.Index(
                        fields=["is_experimental"],
                        name="repositorie_is_expe_70db73_idx",
                    ),
                    models.Index(
                        fields=["last_commit_date"],
                        name="repositorie_last_co_3bdb84_idx",
                    ),
                ],
                "unique_together": {("name", "repository_url")},
            },
        ),
    ]
